services:
  postgres:
    image: postgres:16
    container_name: pieuvre-postgres
    restart: unless-stopped
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-databases.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: pieuvre
      POSTGRES_PASSWORD: ${PG_PASSWORD:-changeme_en_prod}
    networks:
      - pieuvre-net
    shm_size: '256mb'
    command: >
      postgres
        -c shared_buffers=2GB
        -c effective_cache_size=6GB
        -c work_mem=64MB
        -c maintenance_work_mem=512MB
        -c max_connections=200

  mongo:
    image: mongo:7
    container_name: pieuvre-mongo
    restart: unless-stopped
    ports:
      - "0.0.0.0:27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: pieuvre
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-changeme_en_prod}
    networks:
      - pieuvre-net


networks:
  pieuvre-net:
    name: pieuvre-net
    driver: bridge

volumes:
  pg_data:
  mongo_data:
